// Run with Node: desktop-oracle.cjs /path/to/LilacAnime-desktop.
// Expected values come from the desktop working files, not a second implementation.
const fs = require('fs'), path = require('path'), vm = require('vm'), crypto = require('crypto');
const desktop = path.resolve(process.argv[2]), root = path.resolve(__dirname, '../..');
const app = fs.readFileSync(path.join(desktop, 'src/app.js'), 'utf8');
const trackBody = app.match(/function translationSourceTrack\(\)\{[\s\S]*?\n\}/)[0];
const koreanBody = app.match(/function isKoreanTrack\(track\)\{[^\n]+/)[0];
const savedBody = app.match(/const savedPreferred=([^;]+);if\(savedPreferred\)/)[1];
const meta = require(path.join(desktop, 'src/anime-metadata.js'));
const audio = require(path.join(desktop, 'electron/oped-fingerprint.cjs'));
const decode = require(path.join(desktop, 'electron/catalog-updates.cjs')).decodeData;
const track = (label, language = '', url = 'https://fixture.test/sub.ass') => ({label, language, url});
const trackSets = [[], [track('English signs', 'en'), track('English dialogue', 'en')],
  [track('English full', 'en'), track('日本語', 'ja')], [track('English (AI)', 'en'), track('English', 'en')],
  [track('English forced', 'en'), track('English songs', 'en')], [track('French','fr')],
  [track('Custom', 'en-US'), track('Japanese', 'ja-JP')], [track('Default', 'en'), track('English dubtitle', 'en')]];
const korean = [track('한국어'),track('Korean','kor'),track('Custom','ko'),track('Custom','ko-KR'),track('Custom','en','https://fixture.test/x_kor_1.ass'),track('English','en'),track('한국어','en'),track('Custom','kok'),track('Custom','en','https://fixture.test/ko.ass')];
const savedCases = [
  {preferred:'kairan',saved:[{source:'gemini'},{source:'kairan'}]},
  {preferred:'reanime',saved:[{source:'gemini'},{source:'reanime'}]},
  {preferred:'jimaku',saved:[{source:'kairan'},{source:'gemini'},{source:'jimaku'}]},
  {preferred:'csora',saved:[{source:'kairan'}]},
  {preferred:'reanime',saved:[{source:'jimaku'},{source:'gemini'}]}
];
const metadata = [
  {year:2026,season:'FALL',availableEpisodes:0,totalEpisodes:12},
  {year:2026,season:'SPRING',availableEpisodes:4,totalEpisodes:12},
  {year:2026,season:'SUMMER',totalEpisodes:1},
  {year:2026,season:'WINTER'}, {aired:'2025-12-24',year:2026,season:'FALL'},
  {startedOn:'2026-02',availableEpisodes:13,totalEpisodes:0},
  {availableEpisodes:0,totalEpisodes:null}, {aired:'bad',year:2025}
];
function noise(frames, seed) { let x=seed|0; const values=[]; for(let f=0;f<frames;f++){const row=new Float32Array(32);for(let b=0;b<32;b++){x^=x<<13;x^=x>>>17;x^=x<<5;row[b]=x/2147483648}values.push(row)}return values }
const regions = [{frames:1000,from:220,to:410,length:500},{frames:1000,from:0,to:100,length:300},{frames:600,from:10,to:50,length:450},{frames:250,from:0,to:0,length:100}].map(c=>{
  const a=noise(c.frames,123),b=noise(c.frames,456);for(let i=0;i<c.length;i++)b[c.to+i]=a[c.from+i];
  return {...c,expected:audio.findRepeatedRegion(a,b)};
});
const tables = [[{latestAired:1},[2],{id:3,episode:4},'test',{aired:5},['Date','2026-10-08T03:00:00.000Z']], [{a:1,b:1,__proto__:2},'same','ignored'],[[1,2,3],'ok',null,-1]];
const result = {
  subtitleTracks:trackSets.map(tracks=>({tracks,expected:vm.runInNewContext(trackBody+';translationSourceTrack()', {currentPlaybackContext:{subtitleTracks:tracks}})?.label ?? null})),
  korean:korean.map(input=>({input,expected:vm.runInNewContext(koreanBody+';isKoreanTrack(track)',{track:input})})),
  saved:savedCases.map(c=>({...c,expected:vm.runInNewContext(savedBody,c)?.source ?? null})),
  metadata:metadata.map(input=>({input,release:meta.releaseDate(input),label:meta.episodeLabel(input)})), regions,
  svelte:tables.map(input=>({input,expected:decode(input)})),
  pcm:{frames:audio.fingerprint(Float32Array.from({length:24000},(_,i)=>Math.sin(i*.021)+.3*Math.sin(i*.057))).length,
       first:audio.fingerprint(Float32Array.from({length:24000},(_,i)=>Math.sin(i*.021)+.3*Math.sin(i*.057))).slice(0,2).flatMap(x=>Array.from(x))}
};
const target=path.join(root,'iosApp/LilacAnimeTests/Fixtures/desktop-oracle.json');
fs.writeFileSync(target,JSON.stringify(result,null,2)+'\n');
const kotlin = `package com.lilac.anime.shared\n\n// Generated by iosApp/scripts/desktop-oracle.cjs from desktop source.\ninternal val desktopOracle = kotlinx.serialization.json.Json.parseToJsonElement("""\n${JSON.stringify(result)}\n""").jsonObject\n`;
fs.writeFileSync(path.join(root,'shared/src/commonTest/kotlin/com/lilac/anime/shared/DesktopOracleFixture.kt'),kotlin.replace('internal val','import kotlinx.serialization.json.jsonObject\n\ninternal val'));
console.log(`Wrote desktop oracle (${result.subtitleTracks.length+result.korean.length+result.saved.length+result.metadata.length+result.regions.length+result.svelte.length+1} cases)`);
