const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const script = fs.readFileSync(require('node:path').join(__dirname, '../LilacAnime/Resources/ohli-capture.js'), 'utf8');
function page() {
  const messages = [], calls = [], timers = [], events = {}, responses = new Map();
  const doc = {querySelector: () => null, querySelectorAll: () => [], addEventListener: (name, fn) => { events[name] = fn; }};
  class XHR { open() {} addEventListener(name, fn) { this[name] = fn; } }
  const fetch = async function(url, options) {
    calls.push({url, options});
    const entry = await responses.get(String(url));
    if (entry instanceof Error) throw entry;
    return {url: entry?.url || String(url), clone() { return this; }, text: async () => entry?.text || ''};
  };
  const window = {fetch, webkit: {messageHandlers: {lilacMedia: {postMessage: x => messages.push(x)}}}};
  class Observer { constructor(fn) { events.resources = fn; } observe() {} }
  vm.runInNewContext(script, {window, document: doc, location: {href: 'https://cdndania.com/video/episode'}, XMLHttpRequest: XHR, URL, TextDecoder, PerformanceObserver: Observer, performance: {getEntriesByType: () => []}, setInterval: fn => timers.push(fn)});
  return {window, messages, calls, responses, events, doc, timers, XHR};
}
const flush = () => new Promise(resolve => setImmediate(resolve));
(async () => {
  const p = page();
  await p.window.fetch('https://ad.test/6seconds.mp4'); await flush();
  assert.equal(p.messages.length, 0, 'An advertising MP4 must not be published');
  const master = 'https://cdn.test/master.txt?token=fixture';
  p.responses.set(master, {url:'https://cdn.test/episode/master.txt', text:'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1000\n480/index.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=5000\n# comment\n1080/index.m3u8'});
  for (const height of [1080, 480]) p.responses.set(`https://cdn.test/episode/${height}/index.m3u8`, {text:'#EXTM3U\n#EXTINF:1400,\nmain.ts\n#EXT-X-ENDLIST'});
  const options = {credentials:'include', referrerPolicy:'no-referrer'};
  await p.window.fetch(master, options); await flush();
  assert.equal(p.calls[1].options, options, 'Preserve cookie/referrer options');
  assert.deepEqual(p.messages.map(x => x.url), ['https://cdn.test/episode/1080/index.m3u8']);
  assert.ok(p.messages.every(x => x.kind === 'ohliVariant' && x.referer === ''));
  const q = page();
  q.responses.set('https://ad.test/ad.m3u8', {text:'#EXTM3U\n#EXTINF:6,\nad.ts\n#EXT-X-ENDLIST'});
  await q.window.fetch('https://ad.test/ad.m3u8'); await flush(); assert.equal(q.messages.length, 0);
  const xhr = new q.XHR(); xhr.open('GET', '/master.txt');
  q.responses.set('https://cdn.test/redirect/720.m3u8', {text:'#EXTM3U\n#EXTINF:1400,\nmain.ts\n#EXT-X-ENDLIST'});
  xhr.responseURL = 'https://cdn.test/redirect/master.txt'; xhr.responseText = '#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=2000\n720.m3u8'; xhr.load();
  await flush();
  assert.equal(q.messages[0].url, 'https://cdn.test/redirect/720.m3u8');
  const r = page();
  r.window.jwplayer = () => ({getPlaylistItem: () => ({file:'https://ad.test/ad.mp4'}), getDuration: () => 6});
  r.timers[0](); assert.equal(r.messages.length, 0);
  r.window.jwplayer = () => ({getPlaylistItem: () => ({file:'https://cdn.test/episode.mp4'}), getDuration: () => 1440});
  r.timers[0](); assert.equal(r.messages[0].kind, 'ohliMedia');
  const s = page(); s.doc.querySelector = selector => selector === 'iframe#video' ? {src:'https://cdndania.com/video/episode'} : null;
  s.events.DOMContentLoaded(); assert.equal(s.messages[0].kind, 'ohliPlayer');
  const t = page();
  t.responses.set('https://cdn.test/master.txt', new Error('Temporary failure'));
  t.window.jwplayer = () => ({getPlaylistItem: () => ({file:'https://cdn.test/master.txt'})});
  t.timers[0](); await flush(); t.responses.set('https://cdn.test/master.txt', {text:'#EXTM3U\n#EXTINF:40,\nmain.ts\n#EXT-X-ENDLIST'});
  t.timers[0](); await flush(); assert.equal(t.messages[0].url, 'https://cdn.test/master.txt');
  const before = t.calls.length; t.timers[0](); await flush(); assert.equal(t.calls.length, before, 'A loaded master is not fetched every second');
  const u = page();
  u.responses.set('https://cdn.test/native/master.txt', {text:'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1000\nindex.m3u8'});
  u.responses.set('https://cdn.test/native/index.m3u8', {text:'#EXTM3U\n#EXTINF:1400,\nmain.ts\n#EXT-X-ENDLIST'});
  u.events.resources({getEntries: () => [{name:'https://cdn.test/native/master.txt'}]}); await flush();
  assert.equal(u.messages[0].url, 'https://cdn.test/native/index.m3u8', 'Native Safari HLS resource discovery must read master.txt');
  const v = page(), token = 'https://cdndania.com/m3/session-token';
  const media = '#EXTM3U\n#EXTINF:1420,\nhttps://open-cdn.test/1080p_000.html\n#EXT-X-ENDLIST';
  v.responses.set('https://cdndania.com/master.txt', {text:'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=5000000\n'+token});
  v.responses.set(token, {text:media});
  await v.window.fetch('https://cdndania.com/master.txt'); await flush();
  assert.equal(v.messages.length, 1, 'Do not publish an unverified session-only URL');
  assert.equal(v.messages[0].url, token);
  assert.equal(v.messages[0].manifest, media, 'Carry the captured media playlist across the WK/native session boundary');
  assert.equal(v.calls.at(-1).options.credentials, 'include');
  assert.equal(v.calls.at(-1).options.referrerPolicy, 'no-referrer');
  const ranked = page(), root = 'https://cdn.test/ranked/master.txt', high = 'https://cdn.test/ranked/1080.m3u8', low = 'https://cdn.test/ranked/480.m3u8';
  ranked.responses.set(root, {text:'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1000\n480.m3u8\n#EXT-X-STREAM-INF:BANDWIDTH=5000\n1080.m3u8'});
  let releaseHigh;
  ranked.responses.set(high, new Promise(resolve => { releaseHigh = resolve; }));
  ranked.responses.set(low, {text:media});
  await ranked.window.fetch(root); await flush();
  await ranked.window.fetch(low); await flush();
  assert.equal(ranked.messages.length, 0, 'A faster low rendition cannot outrun the desktop quality preference');
  releaseHigh({text:media}); await flush();
  assert.equal(ranked.messages[0].url, high);
  const fallback = page();
  fallback.responses.set(root, ranked.responses.get(root)); fallback.responses.set(high, new Error('Unavailable')); fallback.responses.set(low, {text:media});
  await fallback.window.fetch(root); await flush();
  assert.equal(fallback.messages[0].url, low, 'An unavailable preferred rendition falls back');
  console.log('Ohli capture: advertising isolation, HLS/XHR redirects, ranking, headers, MP4 fallback and retry passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
